### ISSUE TITLE
Grovsortering vis lik info i alle felt

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMprogram#2]
Lag en jQueryfunksjon som kan vise lik info på alle innslag. Dropdown-liste.
F.eks. Vis kategori, Vis kommune osv
Gjør det enklere å grovsortere programmet
![2013-11-27 11 16 59](https://f.cloud.github.com/assets/4747102/1630515/3028a622-574d-11e3-896f-ffcac1f7029e.jpg)

**Comment by AsgeirSH** [comment]
Midlertidig løsning (skrevet på 15 minutter på et trangt kontor i Molde):
![skjermbilde 2016-03-21 kl 17 31 22](https://cloud.githubusercontent.com/assets/1831028/13926023/d34a14f8-ef8a-11e5-9945-578ad9679afb.png)

**Comment by mariusmandal** [comment]
Godt nok, men bør utbedres før festivalen. 
- [ ] Knappen flyttes opp ved "skjul alle detaljer"
- [ ] Må nullstille slik at alle viser samme info

**Comment by mariusmandal** [comment]
Sleng på attr data-showing-index som holder en integer med hvilket felt som skal vises. Iterer deretter over alle elementer, skjul alle og vis child[ data-showing-index ] e.l.

**Comment by AsgeirSH** [comment]
Oooh, elegant!

**Comment by mariusmandal** [comment]
Kan også legge på klassen info-index-i på alle informasjons-div'er.
Dermed vil det være
$(.innslag > div.info).hide( function(){
  $(.innslag > div.info-index-i).show()
});
