### ISSUE TITLE
Dupliser hendelse re-introduseres

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMprogram#20]
Når man redigerer en hendelse, må det være mulig å trykke på en knapp "dupliser hendelse".

Effekt:
- Opprett ny hendelse med samme egenskaper
- Gi den nytt navn (Kopi av $eksisterende_navn)
- Legg til alle innslag med samme rekkefølge

Implementeres i [UKMAPI](https://github.com/UKMNorge/UKMapi) som funksjonen 
`UKMNorge\Arrangement\Program\Write::dupliser( Hendelse $hendelse )`

**Comment by AsgeirSH** [comment]
Ref 
https://github.com/UKMNorge/UKMprogram/tree/feature/dupliserhendelse
https://github.com/UKMNorge/UKMapi/tree/feature/dupliserhendelse

Tar også #21 før jeg oppretter PR :)

**Comment by AsgeirSH** [comment]
Se https://github.com/UKMNorge/UKMprogram/pull/23
og https://github.com/UKMNorge/UKMapi/pull/105
