### ISSUE TITLE
Direktesending

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMprogram#8]
Legg til knapp for "direktesendes" når man håndterer forestillinger. Dette må brukes av direktesending i videomodulen, slik at embedvindu vises kun når det er en direktesendt hendelse.

OBS: legg også til en forklaring om at dette _IKKE_ streamer forestillingen, men gjør at videovinduet vises, i tilfelle de streamer den ;)

**Comment by mariusmandal** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TYw0Ge2Z&#x2F;180-direktesendes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Direktesendes</a>

**Comment by mariusmandal** [comment]
Test av kommentar

**Comment by AsgeirSH** [comment]
Pdd. henter den visningsstatus fra tidspunkt, men bør i stedet kunne velges på hver programhendelse. 

Vis liste over forestillinger - Direktesending ja/nei, default ja.
Lagre de som _ikke_ skal vises.

Flytt til UKMvideo, under fanen Direktesending.

**Comment by AsgeirSH** [comment]
Husk å sjekke opp hvordan triggeren funker.

**Comment by mariusmandal** [comment]
Mulig denne funksjonaliteten bør eksistere under UKMVideo::videresending

UKMprogram bør vise et sammendrag av når hendelsen vises hvis man klikker seg inn på den

**Comment by mariusmandal** [comment]
Har sendt e-post til livestream og spurt pent om vi kan få tilgang til Event-api. I tilfelle kan dette løses med en select-liste for event, hvor ett av valgene er "opprett event"

**Comment by mariusmandal** [comment]
Trenger UKMNorge/UKMapi#114 for å fungere
