### ISSUE TITLE
Innslag fjernet fra mønstring MÅ fjernes fra program

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMprogram#9]
Buskerud har et tilfelle hvor "Prisoners of music" ikke er registrert som deltaker på mønstringen, men står i programmet. Sjekk logger for  hvordan dette er mulig, og utbedre via UKMapi og at alle funksjoner bruker denne!

**Comment by mariusmandal** [comment]
Implementeres i UKMapi V2 og UKMvideresending.
UKMapi V1 ikke nødvendig å integrere

**Comment by AsgeirSH** [comment]
Ser ut til å være fikset, bare med en litt uheldig TODO-kommentar glemt igjen 🙈

**Comment by mariusmandal** [comment]
Fikset også i API V2
